### ISSUE TITLE
CFBundleVersion error

### ISSUE THREAD

**Issue by ottopic** [appcelerator-modules/ti.storekit#42]
I have the error "The hard-coded bundle version does not match the app's CFBundleVersion." 
I have tried Xcode procedure writed on documentation but I get another error, see attachment.

Xcode 14.3.1
SDK 12.1.1.GA

![IMG_2884](https://github.com/tidev/ti.storekit/assets/5537554/42d6985c-58ba-4a31-9c0a-376bea453617)

**Comment by hansemannn** [comment]
The error rather looks like an issue with your app itself. Do you maybe run with LiveView? Please try with a normal build in that case

**Comment by ottopic** [comment]
Is not liveview. This is it complete error building from Xcode.:

> 2023-06-04 17:43:41.167163+0200 MyApp[42181:2997352] [DEBUG] Reading stylesheet from: /private/var/containers/Bundle/Application/0F6F29F2-4175-4709-A978-FB77767A12F4/MyApp.app/stylesheet.plist
2023-06-04 17:43:41.252488+0200 MyApp[42181:2997352] [ERROR] Could not load _index_.json require index, error was File not found
2023-06-04 17:43:41.310539+0200 MyApp[42181:2997352] [INFO] MyApp 3.5.0 (Powered by Titanium 12.1.2.1e3a7d3afb)
2023-06-04 17:43:41.317220+0200 MyApp[42181:2997352] [ERROR] /ti.kernel.js:1073
          fileIndex = JSON.parse(json);
                                 ^
SyntaxError: JSON Parse error: Unexpected identifier "undefined"
    at parse ([native code])
    at filenameExists (/ti.kernel.js:1073:33)
    at require (/ti.kernel.js:757:36)
    at doLoad (/ti.main.js:12870:34)
    at loadBootstrapScripts (/ti.main.js:12893:11)
    at loadAsync (/ti.main.js:12898:23)
    at  (/ti.main.js:12916:10)
    at load (/ti.kernel.js:634:24)
    at  (/ti.kernel.js:1107:18)
    Foundation 0x00000001c5ca71ec _NSDescriptionWithLocaleFunc + 80
    CoreFoundation 0x00000001cba184a4 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 332964
    CoreFoundation 0x00000001cba4b1d4 _CFStringCreateWithFormatAndArgumentsReturningMetadata + 184
    CoreFoundation 0x00000001cba47aac _CFStringCreateWithFormatAndArgumentsAux2 + 44
    TitaniumKit 0x000000010530dce8 TiLogMessage + 52
    TitaniumKit 0x000000010533d2e0 -[TiExceptionHandler reportScriptError:] + 60
    JavaScriptCore 0x00000001df58f83c A246B25E-5C67-3F79-ABF6-DB675D81B7EC + 4798524
    JavaScriptCore 0x00000001df0fe0a0 A246B25E-5C67-3F79-ABF6-DB675D81B7EC + 8352
    TitaniumKit 0x000000010531dadc -[KrollBridge evalFileOnThread:context:] + 340
    TitaniumKit 0x00000001053479e0 -[KrollInvocation invoke:] + 52
    TitaniumKit 0x00000001053482e4 -[KrollContext invoke:] + 84
    TitaniumKit 0x000000010531e2f4 -[KrollBridge didStartNewContext:] + 1084
    TitaniumKit 0x00000001053489bc -[KrollContext main] + 988
    libdispatch.dylib 0x00000001051a0520 _dispatch_call_block_and_release + 32
    libdispatch.dylib 0x00000001051a2038 _dispatch_client_callout + 20
    libdispatch.dylib 0x00000001051b2798 _dispatch_main_queue_drain + 1196
    libdispatch.dylib 0x00000001051b22dc _dispatch_main_queue_callback_4CF + 44
    CoreFoundation 0x00000001cba5fc28 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 625704
    CoreFoundation 0x00000001cba41560 4230C122-42E8-383B-BEEC-EE7B61F8BB61 + 501088
    CoreFoundation 0x00000001cba463ec CFRunLoopRunSpecific + 612

**Comment by hansemannn** [comment]
And the error disappears when you exclude Ti.StoreKit? I have seen this error in the past, but it was rather an invalid require / app bug at the time

**Comment by ottopic** [comment]
No, it doesn't works anyway, with empty app too. I don't know how to go forward.

**Comment by ottopic** [comment]
CFBundleVersion error solved running from cli removing 

```
<key>CFBundleVersion</key>
<string>318</string>
```

from tiapp.xml
